version: "3"
volumes:
  myvolume:
  ftpsharevolume:
services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "${APIPORT}:${APIPORT}"
    volumes:
      - ./backend:/app
    depends_on:
      - db
  db:
    image: postgres:11.13
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - myvolume:/volume/path
    env_file:
      - .env
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "./data:/home/username/"
      - "./passwd:/etc/pure-ftpd/passwd"
    env_file:
      - .env
# uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
#      - "/folder_on_disk/ssl:/etc/ssl/private/"
# or ssl/tls with Let's Encrypt (cert and key as two files)
#      - "/etc/letsencrypt/live/<your_server>/cert.pem:/etc/ssl/private/pure-ftpd-cert.pem"
#      - "/etc/letsencrypt/live/<your_server>/privkey.pem:/etc/ssl/private/pure-ftpd-key.pem"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: "${FTP_USER_NAME}"
      FTP_USER_PASS: "${FTP_USER_PASS}"
      FTP_USER_HOME: "${FTP_USER_HOME}"
# also for ssl/tls:
#      ADDED_FLAGS: "--tls=2"
    restart: always