version: "3"
volumes:
  myvolume:
services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "${APIPORT}:${APIPORT}"
    volumes:
      - ./backend:/app
    depends_on:
      - db
  db:
    image: postgres:11.13
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - myvolume:/volume/path
    env_file:
      - .env